// Copyright (c) 2006 Nigel Tao.
// Licenced under the GNU General Public Licence (GPL) version 2.

#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <stdio.h>
#include <stdlib.h>
#include <X11/keysym.h>
#include <X11/X.h>
#include <X11/Xlib.h>

#include "screen.h"
#include "popup.h"

#ifdef HAVE_DBUS_GLIB
#include "dbus-object.h"
#endif

#ifdef HAVE_XCOMPOSITE
#include "thumbnailer.h"
#endif

//------------------------------------------------------------------------------

// TODO - listen to window manager changes.
gboolean window_manager_uses_viewports = FALSE;

//------------------------------------------------------------------------------

static Window x_root_window = None;
static SSScreen *screen = NULL;
static Popup *popup = NULL;
static int popup_keycode_to_free = -1;
static gboolean show_version_and_exit = FALSE;

//------------------------------------------------------------------------------

static GdkFilterReturn
filter_func (GdkXEvent *gdk_xevent, GdkEvent *event, gpointer data)
{
  XEvent *x_event;
  x_event = (XEvent *) gdk_xevent;

  switch (x_event->type) {
  case KeyPress:
    if (popup == NULL && popup_keycode_to_free == -1) {
      popup_keycode_to_free = x_event->xkey.keycode;
      popup = popup_create (screen);
    } else {
      popup_on_key_press (popup,
                          GDK_DISPLAY_XDISPLAY (gdk_display_get_default ()),
                          &x_event->xkey);
    }
    break;
  case KeyRelease:
    if (popup_keycode_to_free == x_event->xkey.keycode) {
      popup_keycode_to_free = -1;
      popup_free (popup);
      popup = NULL;
    }
    break;
  default:
    // No-op.
    break;
  }

  return GDK_FILTER_CONTINUE;
}

//------------------------------------------------------------------------------

static void
grab (int keyval)
{
  Display *display;
  display = GDK_DISPLAY_XDISPLAY (gdk_display_get_default ());
  XGrabKey (display,
            XKeysymToKeycode (display, keyval),
            AnyModifier,
            x_root_window,
            False,
            GrabModeAsync,
            GrabModeAsync);
}

//------------------------------------------------------------------------------

gboolean
superswitcher_hide_popup (void *object, GError **error)
{
  if (popup) {
    popup_free (popup);
    popup = NULL;
  }
  return TRUE;
}

//------------------------------------------------------------------------------

gboolean
superswitcher_show_popup (void *object, GError **error)
{
  if (!popup) {
    popup = popup_create (screen);
  }
  return TRUE;
}

//------------------------------------------------------------------------------

gboolean
superswitcher_toggle_popup (void *object, GError **error)
{
  if (popup) {
    return superswitcher_hide_popup (object, error);
  } else {
    return superswitcher_show_popup (object, error);
  }
}

//------------------------------------------------------------------------------

int
main (int argc, char **argv)
{
  static const GOptionEntry options[] = {
    { "version", 'v', 0, G_OPTION_ARG_NONE, &show_version_and_exit,
      "Show the version number and exit", NULL },
#ifdef HAVE_XCOMPOSITE
    { "show-window-thumbnails", 't', 0, G_OPTION_ARG_NONE,
      &show_window_thumbnails,
      "EXPERIMENTAL - Show window thumbnails (instead of icons)", NULL },
#endif
    { NULL }
  };

  GdkWindow *root;
  GOptionContext *context;
  GError *error;

  gtk_init (&argc, &argv);

  context = g_option_context_new ("");
  error = NULL;
  g_option_context_add_main_entries (context, options, NULL);
  g_option_context_parse (context, &argc, &argv, &error);

  if (error) {
    g_printerr ("%s\n", error->message);
    g_error_free (error);
    exit (ABNORMAL_EXIT_CODE_UNKNOWN_COMMAND_LINE_OPTION);
  }

  if (show_version_and_exit) {
    // VERSION comes from the Makefile generated by autogen.sh and configure.in.
    printf ("SuperSwitcher version %s\n", VERSION);
    return 0;
  }

#ifdef HAVE_DBUS_GLIB
  // Note that this may exit(...) if another instance is already running.
  init_superswitcher_dbus ();
#endif

#ifdef HAVE_XCOMPOSITE
  if (show_window_thumbnails) {
    show_window_thumbnails = init_composite ();
  }
#endif

  root = gdk_get_default_root_window ();
  x_root_window = GDK_WINDOW_XWINDOW (root);

  gdk_window_add_filter (root, filter_func, NULL);
  grab (XK_Super_L);
  grab (XK_Super_R);

  screen = ss_screen_new (wnck_screen_get_default (),
                          GDK_DISPLAY_XDISPLAY (gdk_display_get_default ()),
                          x_root_window);

  gtk_main ();

#ifdef HAVE_XCOMPOSITE
  if (show_window_thumbnails) {
    uninit_composite ();
  }
#endif

  return 0;
}
